platform :ios, '8.0'

target 'Sample' do
  use_frameworks!

  # Pods for Sample
  pod 'PhoneNumberKit', :git => "https://github.com/SimformSolutionsPvtLtd/PhoneNumberKit.git", :branch => 'feature/ondex'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
